"""esquema inicial

Revision ID: c5015ea6a1fa
Revises: 
Create Date: 2026-09-01 16:43:39.830556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5015ea6a1fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_rejects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('node_id', sa.String(length=8), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_rejects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_rejects_node_id'), ['node_id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('apiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('inmet_station', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=8), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('firmware_version', sa.String(length=40), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_node_id'), ['node_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('meliponicultor', 'pesquisador', 'admin', name='role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('sensor', sa.String(length=20), nullable=False),
    sa.Column('offset', sa.Float(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apiary_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('species', sa.String(length=120), nullable=True),
    sa.Column('box_type', sa.String(length=120), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['apiary_id'], ['apiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=True),
    sa.Column('species', sa.String(length=120), nullable=True),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('comparison', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('sustained_samples', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('node_id', sa.String(length=8), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('temp_in_c', sa.Float(), nullable=True),
    sa.Column('temp_out_c', sa.Float(), nullable=True),
    sa.Column('rh_in_pct', sa.Float(), nullable=True),
    sa.Column('rh_out_pct', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('vbat_v', sa.Float(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('snr', sa.Float(), nullable=True),
    sa.Column('sound_rms', sa.Float(), nullable=True),
    sa.Column('gateway_id', sa.String(length=32), nullable=True),
    sa.Column('quality_flags', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'seq', name='uq_measurements_node_seq')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurements_hive_id'), ['hive_id'], unique=False)
        batch_op.create_index('ix_measurements_hive_time', ['hive_id', 'time'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_time'), ['time'], unique=False)

    op.create_table('node_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sensor_placement', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('protocol_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_assignments_node_period', ['node_id', 'installed_at'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_hive_id'), ['hive_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_hive_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('node_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_assignments_node_period')

    op.drop_table('node_assignments')
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurements_time'))
        batch_op.drop_index('ix_measurements_hive_time')
        batch_op.drop_index(batch_op.f('ix_measurements_hive_id'))

    op.drop_table('measurements')
    op.drop_table('alert_rules')
    op.drop_table('hives')
    op.drop_table('calibrations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_node_id'))

    op.drop_table('nodes')
    op.drop_table('apiaries')
    op.drop_table('organizations')
    with op.batch_alter_table('ingest_rejects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_rejects_node_id'))

    op.drop_table('ingest_rejects')
    # ### end Alembic commands ###
